require 'rubygems'
require 'fileutils'
require './lib/quick_books_sync/acts_as_quick_books_resource'

SPEC_DIR = File.expand_path(File.dirname(__FILE__) + '/spec')
require 'spec/rake/spectask'
Spec::Rake::SpecTask.new(:spec) do |t|
  t.spec_files = FileList[SPEC_DIR + '/**/*_spec.rb']
  t.spec_opts = ["--format specdoc"]
end

task :default => [:spec]

